steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA', '.']
  env:
  - 'NODE_ENV=dev'
  - 'ATLAS_URI=mongodb+srv://ranaditya2011:Swastik%402003@cluster0.zxgjx4k.mongodb.net/lisiatech-db?authMechanism=DEFAULT'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'product-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--update-env-vars'
  - 'NODE_ENV=dev,ATLAS_URI=mongodb+srv://ranaditya2011:Swastik%402003@cluster0.zxgjx4k.mongodb.net/lisiatech-db?authMechanism=DEFAULT'
images:
- gcr.io/$PROJECT_ID/product-service:$COMMIT_SHA